### PR TITLE
Remove hide_action calls

### PR DESCRIPTION
**Pull request by ekampp**
This method has been removed in Rails 5, see
https://github.com/rails/rails/issues/18336

### CODE REVIEW

**Comment by mattpolito** [comment]
@ekampp Great catch on `hide_action` being deprecated! It looks like these `hide_action` calls were trying to protect the methods from the outside world. Now that they are removed in this commit that protection would be missing as well. Can you adjust to get back that intended functionality?

**Comment by ekampp** [comment]
What was the point of hiding actions from the implementing controller in the first place? From DHH's comment it seems that `hide_action` was used to hide actions from being exposed accedentally through the router, this has been fixed in a centralized manner. 

So now that the methods defined in decent exposure is no longer available to the public without explicit definition in the router hiding them from the outside world has automatically been accomplished.

**Comment by mattpolito** [comment]
@ekampp Thanks for your clarification. It does appear that all public methods in a controller are still exposed as actions. That is even stated in the PR. I believe to finish up this PR making those methods private would be enough. Please let me know if I am missing something that would make that unnecessary.

**Comment by mattpolito** [comment]
Merged

**Comment by ekampp** [comment]
Nice. Thanks :+1:

**Pull request closed without merging**
