### PR TITLE
Create instance and apply params separately

### LINKED ISSUE #191: Initialise and assign attributes separately
What would you think of separating these two steps?

https://github.com/hashrocket/decent_exposure/blob/master/lib/decent_exposure/behavior.rb#L64

So instead:

```
def build(params, scope)
  instance = scope.new
  instance.attribiutes = params

  instance
end
```

The reason is subtle, but the build association is not accessible until after the object has been initialised, so if something wants access to the association in any of the attribute assignment methods it won't have it yet.

In my specific case, I have a Paperclip processor that needs something from the instance's associated parent object, and Paperclip processors do all their work when the parameter is applied rather than waiting until the instance is saved, and thus because the association isn't available yet, it all blows up.

The above code is basically functionally identical to the existing code except that it allows the instance to initialise (and assign its parent association), then assigns the attributes after that.

### PR DESCRIPTION
**Pull request by brendon**
First creating the instance, then applying the parameters allows us to work around a quirk in `active_record` where the relations aren't established on the object until after the parameters are applied. This means if any of our attribute setters reference the relation, they will fail if we don't seperate these steps.

Points to consider:
- The `attributes` method may not exist on non-active_record exposures. Are we assuming too much?
- In your feature spec file, the `BirdsController` isn't thrown away between each test, so redefining something like `expose :bird` can break other tests in a non-deterministic way (due to test ordering). It hasn't been exposed yet because you don't redefine any exposures in your tests, but just wanted to give a heads-up as I ran into this when trying to redefine `:bird`. A seperate controller class per test would probably work best to avoid this problem.
- I had to adjust a lot of controller tests to cope with the new expectation that we'll always call `new` without arguments, and then subsequently call `attributes=`.

Fixes #191

### CODE REVIEW

**Comment by mattpolito** [comment]
@brendon Thank you very much for putting the time into this PR. After looking through it I'm realizing that DecentExposure has users that don't always use an ActiveRecord with this API. We cannot rely on `#attributes` to be there.

**Comment by brendon** [comment]
That's correct. AR also isn't a dependency. I guess there's two options, close the PR, or look at extending `Behavior` so that it checks if the object: `method_defined? :attributes=` and acts accordingly. Up to you :)

**Comment by mattpolito** [comment]
This seems to specifically be an ActiveRecord issue. Why don’t you try out the logic if the object is an AR. See how that feels. That will remove the changes from the tests and then we can have a specific test case for the new functionality.

**Comment by brendon** [comment]
Hi @mattpolito, just been working on this. There is an issue that we need to actually test for both ActiveRecord::Base and ActiveRecord::Relation as we may have either as a scope. It's a bit long winded but I'll commit what I've got and perhaps you'll have some ideas on making it cleaner?

**Comment by brendon** [comment]
Just pinging this one. Starting a new project and was considering using decent_exposure on it :D

**Comment by mattpolito** [comment]
@brendon Thanks for pinging this. I never saw your updates come through. I'll look over the changes today and hopefully I can get this in for you.

Thank you.

**Comment by mattpolito** [comment]
Closing reasoning in #191

**Pull request closed without merging**
