### PR TITLE
Rails41 test

### PR DESCRIPTION
**Pull request by arthurnn**
3 commits here, they are pretty self-explanatory

### CODE REVIEW

**Comment by jgdavey** [comment]
It looks like the build failed. Could you take a look at that? Thanks!

**Comment by arthurnn** [comment]
Not sure what the issue is... failing for jruby on rails 3.2 , I would say a retry should fix the problem.

**Comment by southwolf** [comment]
Didn't look into it thoroughly, but seems to be RSpec problem? Error message was: "unknown option --format"

**Comment by arthurnn** [comment]
closing this, as it is pretty old

**Pull request closed without merging**
